### PR TITLE
Add inline function for AnnotationReplacers & fix issue #14

### PR DESCRIPTION
**Pull request by GrowlyX**

### CODE REVIEW

**Comment by GrowlyX** [comment]
The second commits fixes locales on legacy spigot versions. (https://github.com/Revxrsal/Lamp/issues/14)

**Comment by Revxrsal** [comment]
LGTM, thanks!

**Comment by devrawr** [comment]
Keep in mind commit https://github.com/Revxrsal/Lamp/pull/15/commits/d8668a9f85ac78b8ae9487b7876b01166da19c64 makes it incompatible with Bukkit, but (as far as I know) there is a `locale` field within the EntityPlayer class if you wish to support bukkit (which I assume you do, considering the module name is `bukkit`). 

Not sure if this field exists in every version, but most versions I was able to find contain it:
* https://github.com/styk-tv/Craftbukkit/blob/c23090ec4785fb015f735fb3d03f10eee6eb0873/src/main/java/net/minecraft/server/EntityPlayer.java#L33
* https://github.com/Attano/Spigot-1.8/blob/9db48bc15e203179554b8d992ca6b0a528c8d300/net/minecraft/server/v1_8_R3/EntityPlayer.java#L30 (not entirely sure why it has a Spigot comment, considering the line I sent above.)

Rather simple reflection should be able to retrieve this field.

**Comment by GrowlyX** [comment]
> Keep in mind commit [d8668a9](https://github.com/Revxrsal/Lamp/commit/d8668a9f85ac78b8ae9487b7876b01166da19c64) makes it incompatible with Bukkit, but (as far as I know) there is a `locale` field within the EntityPlayer class if you wish to support bukkit (which I assume you do, considering the module name is `bukkit`).

Although my pull request was merged, @Revxrsal pushed an additional commit with additional code allowing for fallback locales if an exception is thrown & the use of the modern `Player#getLocale` method if available. 

Here's the commit: [Fix #14](https://github.com/Revxrsal/Lamp/commit/7c0d05fd958fe4cbbdbbcf01c5b622c25d0b359d)

**Pull request merged**
