### PR TITLE
Added Portuguese language support

### PR DESCRIPTION
**Pull request by alisson0022**

### CODE REVIEW

**Comment by Revxrsal** [comment]
Looks great to me! Do you think you could possibly provide translations for other modules as well (like [this](https://github.com/alisson0022/Lamp/blob/pt-language/bukkit/src/main/resources/lamp-bukkit_en.properties))? They don't contain many locales and many of them are repeated on other Minecraft platforms

**Comment by alisson0022** [comment]
Oh, I actually didn't see them 😅. I'll definitely do a translation for them too

**Comment by alisson0022** [comment]
I've added the missing translations

**Comment by Revxrsal** [comment]
Looks good to me, thanks!

**Pull request merged**
