### PR TITLE
Sponge 8 Base Support.

### PR DESCRIPTION
**Pull request by creatorfromhell**
This has not been tested yet.

### CODE REVIEW

**Comment by creatorfromhell** [comment]
Few quarks when testing this. For some reason, the listener in the command system here doesn't get called so there may be some workarounds needed. I'm going to test adding the initializer before the GameEngine starts, which could lead to some interesting results, as any calls to Sponge.server will need moved out of the constructor.

**Comment by creatorfromhell** [comment]
Update here: I got it loading, and commands are able to be utilized in-game.

Things that currently don't work:
- command permission
- Auto Completion(See error below)
`> Complete: gi
[08:37:13] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalStateException: Path cannot be empty!
        at net.tnemc.libs.lamp.commands.util.Preconditions.notEmpty(Preconditions.java:40) ~[Preconditions.class:?]
        at net.tnemc.libs.lamp.commands.core.CommandPath.get(CommandPath.java:76) ~[CommandPath.class:?]
        at net.tnemc.libs.lamp.commands.core.BaseAutoCompleter.complete(BaseAutoCompleter.java:133) ~[BaseAutoCompleter.class:?]
        at net.tnemc.libs.lamp.commands.sponge.core.SpongeCommandCallable.complete(SpongeCommandCallable.java:54) ~[SpongeCommandCallable.class:?]
        at org.spongepowered.common.command.registrar.SpongeRawCommandRegistrar.complete(SpongeRawCommandRegistrar.java:99) ~[SpongeRawCommandRegistrar.class:1.16.5-8.1.0-RC1352]
        at org.spongepowered.common.util.CommandUtil.createSuggestionsForRawCommand(CommandUtil.java:83) ~[CommandUtil.class:1.16.5-8.1.0-RC1352]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handler$zgm000$impl$getSuggestionsFromNonBrigCommand(ServerGamePacketListenerImpl.java:3309) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomCommandSuggestions(ServerGamePacketListenerImpl.java:481) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.handle(ServerboundCommandSuggestionPacket.java:35) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.handle(ServerboundCommandSuggestionPacket.java:9) ~[?:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:262) ~[PacketPhaseUtil.class:1.16.5-8.1.0-RC1352]
        at net.minecraft.network.protocol.PacketUtils.md2e3e77$lambda$tracker$redirectProcessPacket$0$0(PacketUtils.java:552) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:144) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapAndPerformContextSwitch(MinecraftServer.java:4322) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:761) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:155) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:743) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:737) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:722) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:674) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:257) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]`

**Comment by creatorfromhell** [comment]
Nvm, figured it out, the command name is not provided during the completion arguments.
image
Works now.

**Comment by creatorfromhell** [comment]
@Revxrsal This is ready for review, I've attached the screenshot above of my  test with it using TNE for Sponge 8. I've also attached the built jar below.
[sponge-8-3.1.5.zip](https://github.com/Revxrsal/Lamp/files/12155847/sponge-8-3.1.5.zip)

**Comment by Revxrsal** [comment]
Excellent work! I'm glad you didn't need to change much.

**Pull request merged**
